# Generated by Django 4.2.7 on 2025-09-16 06:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botsettings',
            options={'verbose_name': 'Настройки бота', 'verbose_name_plural': 'Настройки бота'},
        ),
        migrations.AlterModelOptions(
            name='botuser',
            options={'verbose_name': 'Пользователь бота', 'verbose_name_plural': 'Пользователи бота'},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['name_uz'], 'verbose_name': 'Филиал', 'verbose_name_plural': 'Филиалы'},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Чек', 'verbose_name_plural': 'Чеки'},
        ),
        migrations.AlterField(
            model_name='botsettings',
            name='instagram_profile_url',
            field=models.URLField(default='https://instagram.com/', help_text='Ссылка на Instagram профиль, на который пользователи должны подписаться', verbose_name='Instagram профиль'),
        ),
        migrations.AlterField(
            model_name='botsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram аккаунт'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='is_subscribed_instagram',
            field=models.BooleanField(default=False, verbose_name='Подписан на Instagram'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='language',
            field=models.CharField(choices=[('uz', "O'zbekcha"), ('qq', 'Qaraqalpaqsha')], default='uz', max_length=2, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='telegram_id',
            field=models.BigIntegerField(unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='address_qq',
            field=models.TextField(verbose_name='Адрес (Каракалпакский)'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='address_uz',
            field=models.TextField(verbose_name='Адрес (Узбекский)'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name_qq',
            field=models.CharField(max_length=200, verbose_name='Название (Каракалпакский)'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name_uz',
            field=models.CharField(max_length=200, verbose_name='Название (Узбекский)'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='bot_management.branch', verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='file',
            field=models.FileField(upload_to='receipts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Файл чека'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='file_size',
            field=models.PositiveIntegerField(verbose_name='Размер файла'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отклонения'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Одобрен'), ('rejected', 'Отклонен')], default='pending', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='bot_management.botuser', verbose_name='Пользователь'),
        ),
    ]
